const data = {
  products: [
    {
      _id: '1',
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '/images/d1.jpg',
      price: 60,
      brand: 'vanheusen',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '/images/d2.jpg',
      price: 58,
      brand: 'vanheusen',
      rating: 5,
      numReviews: 19,
      countInStock: 5,
    },
    {
      _id: '3',
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '/images/d3.jpg',
      price: 62,
      brand: 'vanheusen',
      rating: 4.5,
      numReviews: 10,
      countInStock: 7,
    },
    {
      _id: '4',
      name: 'casual Shirt',
      category: 'Shirts',
      image: '/images/d4.jpg',
      price: 45,
      brand: 'vanheusen',
      rating: 4.4,
      numReviews: 11,
      countInStock: 8,
    },
    {
      _id: '5',
      name: 'casual Shirt',
      category: 'Shirts',
      image: '/images/d5.jpg',
      price: 72,
      brand: 'vanheusen',
      rating: 4.6,
      numReviews: 16,
      countInStock: 5,
    },
    {
      _id: '6',
      name: 'casual Shirt',
      category: 'Shirts',
      image: '/images/d6.jpg',
      price: 56,
      brand: 'vanheusen',
      rating: 4.7,
      numReviews: 14,
      countInStock: 4,
    },
    {
      _id: '7',
      name: 'v-neck t-Shirt',
      category: 't-Shirts',
      image: '/images/d7.jpg',
      price: 51,
      brand: 'vanheusen',
      rating: 4.8,
      numReviews: 12,
      countInStock: 7,
    },
    {
      _id: '8',
      name: 'v-neck t-Shirt',
      category: 't-Shirts',
      image: '/images/d8.jpg',
      price: 54,
      brand: 'vanheusen',
      rating: 4.9,
      numReviews: 11,
      countInStock: 6,
    },
    {
      _id: '9',
      name: 'collar t-Shirt',
      category: 't-Shirts',
      image: '/images/d9.jpg',
      price: 45,
      brand: 'vanheusen',
      rating: 4.3,
      numReviews: 16,
      countInStock: 10,
    },
    {
      _id: '10',
      name: 'fit pants',
      category: 'Pants',
      image: '/images/d10.jpg',
      price: 53,
      brand: 'vanheusen',
      rating: 4.5,
      numReviews: 20,
      countInStock: 6,
    },
    {
      _id: '11',
      name: 'jean pants',
      category: 'Pants',
      image: '/images/d11.jpg',
      price: 55,
      brand: 'vanheusen',
      rating: 4,
      numReviews: 10,
      countInStock: 16,
    },
    {
      _id: '12',
      name: 'casual pants',
      category: 'Pants',
      image: '/images/d12.jpg',
      price: 59,
      brand: 'vanheusen',
      rating: 5,
      numReviews: 15,
      countInStock: 9,
    },
  ],
};
export default data;
